### Request 1
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gabriel Brogni",
  "email": "harden13brogni@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "harden13brogni@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 3",
  "content": "conteúdo da pergunta"
}

###

# @name fetch_accommodations
GET {{baseUrl}}/accommodations?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name create_question
PUT {{baseUrl}}/questions/75ef2457-f08a-454c-8c23-e2877e69b12a
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 3 editada",
  "content": "conteúdo da pergunta 3 editada"
}