### Request 1
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "123@gmail.com",
  "cpf": "12345678900",
  "name": "Gabriel Brogni",
  "phone": "123456789",
  "password": "123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "123@gmail.com",
  "password": "123"
}

###

# @name create_pix
POST {{baseUrl}}/reservations/pix
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "value": 100,
  "city": "City Name",
  "key": "13072038929"
}

###

# @name fetch_accommodations
GET {{baseUrl}}/accommodations?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
